### ISSUE TITLE
Reading Lesson setup as a Lab Lesson

### ISSUE THREAD

**Issue by sandyvern** [learn-co-curriculum/namespaced-routes-reading#10]
This lesson is a reading but it is set up as if it is a lab. If you run learn, it tests for 6 test...none of which are part of what is being done in the reading.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials, removed the tests from this lesson, and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
