### ISSUE TITLE
Error while running bundle install/learn open

### ISSUE THREAD

**Issue by jhharwood88** [learn-co-curriculum/namespaced-routes-reading#12]
/ ♥ learn open
Looking for lesson...
Forking lesson...
Cloning lesson...
Opening lesson...
Bundling...
Fetching gem metadata from https://rubygems.org/.............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    rails (~> 4.2) was resolved to 4.2.11.1, which depends on
      bundler (>= 1.3.0, < 2.0)

  Current Bundler version:
    bundler (2.0.1)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (>= 1.3.0, < 2.0)', which is required by gem 'rails
(~> 4.2)', in any of the sources.

Bundler could not find compatible versions for gem "ruby":
  In Gemfile:
    ruby

    capybara was resolved to 3.21.0, which depends on
      ruby (>= 2.4.0)

    rails (~> 4.2) was resolved to 4.2.11.1, which depends on
      ruby (>= 1.9.3)
Done.

Installing an earlier version of bunlder, 1.9.9, and running bundle install clears the rails gem dependencies but im also hitting an error for ruby now in 

[14:27:07] (master) namespaced-routes-reading-online-web-ft-031119
// ♥ gem install bundler -v 1.9.9
Fetching bundler-1.9.9.gem
Successfully installed bundler-1.9.9
Parsing documentation for bundler-1.9.9
Installing ri documentation for bundler-1.9.9
Done installing documentation for bundler after 1 seconds
1 gem installed
[14:28:14] (master) namespaced-routes-reading-online-web-ft-031119
// ♥ bundle _1.9.9_ install
Fetching gem metadata from https://rubygems.org/..............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies..............
Using rake 12.3.2
Using concurrent-ruby 1.1.5
Using i18n 0.9.5
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 4.2.11.1
Using builder 3.2.3
Using erubis 2.7.0
Using mini_portile2 2.4.0
Using nokogiri 1.10.3
Using rails-deprecated_sanitizer 1.0.3
Using rails-dom-testing 1.0.9
Using crass 1.0.4
Using loofah 2.2.3
Using rails-html-sanitizer 1.0.4
Using actionview 4.2.11.1
Using rack 1.6.11
Using rack-test 0.6.3
Using actionpack 4.2.11.1
Using globalid 0.4.2
Using activejob 4.2.11.1
Using mini_mime 1.0.1
Using mail 2.7.1
Using actionmailer 4.2.11.1
Using activemodel 4.2.11.1
Using arel 6.0.4
Using activerecord 4.2.11.1
Using public_suffix 3.1.0
Using addressable 2.6.0
Using debug_inspector 0.0.3
Using binding_of_caller 0.8.0
Using bundler 1.9.9
Using byebug 11.0.1
Using regexp_parser 1.5.1
Using xpath 3.2.0

Gem::RuntimeRequirementNotMetError: capybara requires Ruby version >= 2.4.0. The current ruby version is 2.3.7.456.
An error occurred while installing capybara (3.21.0), and Bundler cannot
continue.
Make sure that `gem install capybara -v '3.21.0'` succeeds before bundling.

At this point im not sure what i need to do to get this lab running without potentially causing more issues. Will report if i find a solution.

**Comment by jhharwood88** [comment]
This lab appears to be running on rails 4.2, I removed the version dependency and was able to run bundle install without using an older version.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
