### ISSUE TITLE
sqlite3 not working.

### ISSUE THREAD

**Issue by Allenfp** [learn-co-curriculum/namespaced-routes-reading#13]
Due to strange rails error, the Gemfile needs to be updated to the following:

`gem 'sqlite3', '~> 1.3.13'`

See here for details: https://github.com/sparklemotion/sqlite3-ruby/issues/249

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
