### ISSUE TITLE
repo doesn't appear to match lesson content.

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/namespaced-routes-reading#9]
the repo associated with this lesson doesn't deal with namespacing or a blog/admin topic?

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
